# Generated by Django 4.2.7 on 2023-11-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbooks',
            name='book_title',
            field=models.CharField(max_length=250),
        ),
    ]
