# Generated by Django 4.2.7 on 2023-11-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='section',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='total_credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='total_due',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
