# Generated by Django 4.2.7 on 2023-12-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_library',
            new_name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_finance',
        ),
    ]
