# Generated by Django 4.2.7 on 2023-11-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_alter_textbooks_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='textbooks',
            field=models.ManyToManyField(to='homeapp.textbooks'),
        ),
    ]
