# Generated by Django 4.2.7 on 2023-12-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_rename_is_library_user_is_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='total_credit',
        ),
        migrations.RemoveField(
            model_name='students',
            name='total_due',
        ),
    ]
