# Generated by Django 4.2.7 on 2023-11-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_alter_students_section_alter_students_total_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentapplication',
            name='application_id',
            field=models.CharField(default='app_890114', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.CharField(default='std_957817', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='textbooks',
            name='book_id',
            field=models.CharField(default='txt_238530', max_length=250, unique=True),
        ),
    ]
