# Generated by Django 4.2.7 on 2023-11-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_students_textbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='students',
            name='is_not_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='students',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textbooks',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
