# Generated by Django 4.2.7 on 2023-12-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_remove_students_total_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbookstatus',
            name='previous_status',
        ),
        migrations.RemoveField(
            model_name='textbookstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='textbookstatus',
            name='collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textbookstatus',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='textbooks',
            name='book_title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
