# Generated by Django 4.2.7 on 2023-11-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_students_is_collected_students_is_not_collected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbooks',
            name='is_checked',
        ),
    ]
