# Generated by Django 4.2.7 on 2023-12-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_remove_textbookstatus_previous_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='classname',
            field=models.CharField(choices=[('form1', 'Form 1'), ('form2', 'Form 2'), ('form3', 'Form 3'), ('form4', 'Form 4'), ('form5', 'Form 5')], max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='textbooks',
            name='book_title',
            field=models.CharField(max_length=250),
        ),
    ]
