# Generated by Django 4.2.7 on 2023-11-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_remove_textbooks_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='is_not_collected',
            field=models.BooleanField(default=True),
        ),
    ]
