# Generated by Django 4.2.7 on 2023-12-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_alter_classname_classname_alter_textbooks_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
    ]
