# Generated by Django 4.2.7 on 2023-11-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_alter_students_is_not_collected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='is_collected',
        ),
        migrations.RemoveField(
            model_name='students',
            name='is_not_collected',
        ),
        migrations.RemoveField(
            model_name='students',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='textbooks',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textbooks',
            name='is_not_collected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='textbooks',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
