# Generated by Django 4.2.7 on 2023-11-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_alter_paymentapplication_application_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentapplication',
            name='application_id',
            field=models.CharField(default='app_985757', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='section',
            field=models.CharField(blank=True, choices=[('sec_a', 'Section A'), ('sec_b', 'Section B'), ('sec_c', 'Section C'), ('sec_d', 'Section D'), ('sec_e', 'Section E')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.CharField(default='std_226944', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='textbooks',
            name='book_id',
            field=models.CharField(default='txt_312895', max_length=250, unique=True),
        ),
    ]
