# Generated by Django 4.2.7 on 2023-11-20 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_remove_students_is_collected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbooks',
            name='is_collected',
        ),
        migrations.RemoveField(
            model_name='textbooks',
            name='is_not_collected',
        ),
        migrations.RemoveField(
            model_name='textbooks',
            name='is_returned',
        ),
        migrations.CreateModel(
            name='StudentTextbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('not_collected', 'Not Collected'), ('returned', 'Returned')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.students')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.textbooks')),
            ],
        ),
    ]
