# Generated by Django 4.2.7 on 2023-11-30 02:57

from django.db import migrations, models
import homeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_alter_paymentapplication_application_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentapplication',
            name='application_id',
            field=models.CharField(default=homeapp.models.generate_unique_id, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.CharField(default=homeapp.models.generate_unique_id, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='textbooks',
            name='book_id',
            field=models.CharField(default=homeapp.models.generate_unique_id, max_length=250, unique=True),
        ),
    ]
