# Generated by Django 4.2.7 on 2023-11-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_remove_textbooks_is_collected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='textbooks',
            field=models.ManyToManyField(blank=True, null=True, to='homeapp.textbooks'),
        ),
    ]
