# Generated by Django 4.2.7 on 2023-11-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_alter_students_textbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='textbooks',
            field=models.ManyToManyField(blank=True, to='homeapp.textbooks'),
        ),
    ]
