# Generated by Django 4.2.7 on 2023-11-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_alter_students_textbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='classname',
            field=models.CharField(choices=[('grade1', 'Grade 1'), ('grade2', 'Grade 2'), ('grade3', 'Grade 3'), ('grade4', 'Grade 4'), ('grade5', 'Grade 5')], max_length=250),
        ),
    ]
