# Generated by Django 4.2.7 on 2023-11-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_alter_textbooks_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='classname',
            field=models.CharField(choices=[('form1', 'Form 1'), ('form2', 'Form 2'), ('form3', 'Form 3'), ('form4', 'Form 4'), ('form5', 'Form 5')], max_length=250),
        ),
    ]
